controller_frequency: 5.0
recovery_behaviour_enabled: true

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TrajectoryPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_theta:  3.2

  max_vel_x: 1.0 #This parameter defines maximum linear velocity that will be set by trajectory planner.
  min_vel_x: 0.0 #parameter defines minimum linear velocity that will be set by trajectory planner

  max_vel_theta: 1.0 #maximum angular velocity that will be set by trajectory planner
  min_vel_theta: -1.0 #minimum angular velocity that will be set by trajectory planner
  min_in_place_vel_theta: 0.2

  holonomic_robot: false
  escape_vel: -0.1

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.02
  angular_sim_granularity: 0.02
  vx_samples: 6
  vtheta_samples: 20
  controller_frequency: 20.0

  # Trajectory scoring parameters
  meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
  occdist_scale:  0.1 # The weighting used to determine how hard the controller should try to avoid obstacles. 0.01 by default
  pdist_scale: 0.75  #   The weighting for how closely the controller should adhere to the path supplied to it. 0.6 by default
  gdist_scale: 1.0 #     The weighting determines how hard the controller should try to attain its local objective, which also impacts speed. The default value is 0.8.

  heading_lookahead: 0.325  #When rating different in-place rotation trajectories, how far ahead in metres should you look?
  heading_scoring: false  #Whether to rate the robot based on its proximity to the path or its distance from the path. false by default
  heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
  dwa: true #Whether to use the Dynamic Window Approach (DWA)_ or  Trajectory Rollout is used
  simple_attractor: false
  publish_cost_grid_pc: true  

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.25 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
  escape_reset_dist: 0.1
  escape_reset_theta: 0.1

DWAPlannerROS:
  # Robot configuration parameters 
  #The parameters specify the maximum acceleration values utilised by the trajectory planner. 
  acc_lim_x: 2.5
  acc_lim_y: 0
  acc_lim_th: 3.2

  max_vel_x: 0.5
  min_vel_x: 0.0
  max_vel_y: 0
  min_vel_y: 0

  max_vel_trans : 0.5
  min_vel_vel: 0.1
  max_vel_theta : 1.0
  min_vel_theta : 0.2

  # Goal Tolerance Parameters
  # These parameters specify the distance from the destination that can be deemed reached. Linear tolerance is measured in metres, whereas angular tolerance is measured in radians.
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: false

